### ISSUE TITLE
Start all odoo services and nginx and psotgres only in highest runlevel for easy update

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/odoo_v8.0#26]
to make the update simpler we should set all the odoo services (nginx, postgresql, odoo services, aroo helper) to the highest runlevel so we can switch the runlevel update the codebase and switch the runlevel back

**Comment by winston6071** [comment]
git...
lokales "joeslocal" weggesichert 
git add -am addons-thirdparty/themegrpahene "[ADD] add themegraphen...."
deleted pyc files ... 
git status --> GUT 
checkout master 
git status --> GUT 
vergleich mit github --> anderer commit nummer
git fetch --> see diffs 
git pull 
git submodule update
git status alles gut bis auf modfied odoo
FRAGE an MIKE --> was ich mit dem modified odoo ist ein style.css file 
git branch imp26
git checkout imp26
ändern der odoo-tools.sh
aufsetzen lokaler linux virtual box und testen

**Comment by winston6071** [comment]
Run lvl 2 is standard
run level 4 would be best place to stop services ..
init 4 should to the work then in runtime 
STATUS ... testing

**Comment by winston6071** [comment]
last change was the deletion of the runlevel scripts first before changing the levels cause the installation of Nginx Postgresql creates already a runlevel script with their defaults and stop start parameter of update-rc.d does not change existing values .....
