### ISSUE TITLE
Simple Checkout finish into module

### ISSUE THREAD

**Issue by winston6071** [OpenAT/odoo_v8.0#28]
code am pfotdemo server 
/addons/website_sale/controllers/main.py
oder mail andi 25. feb.
FEHLER: das mal was falsches im korb ist..... 
derzeit ist der code mit product.product, deshalb müsste man dann beim linken die ID der Produktvariante nehmen.... 
oder man baut den code auf product.template um

**Comment by michaelkarrer81** [comment]
bitte folgenden Code im Modul website_sale/controllers/main.py in der Klasse "website_sale(http.Controller)" einfügen:

@http.route(['/shop/simplecheckout/<model("product.product"):product>'], type='http', auth="public", website=True, multilang=True)
    def simplecheckout(self, product, **kwargs):
        cr, uid, context, pool = request.cr, request.uid, request.context, request.registry
        
        # First empty cart:
        request.website.sale_reset(context=context)

        order = request.website.sale_get_order(force_create=1)
        order._cart_update(product_id=int(product.id), add_qty=0, set_qty=1)

        return request.redirect('/shop/checkout')


example.com/shop/simplecheckout/3 oder
example.com/shop/simplecheckout/Das-ist-mein-super-produkt-3
