### ISSUE TITLE
Website Mobile Responsiveness error in Microsoft phone or iexplore scales 100% of image 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/odoo_v8.0#33]
Testing: 
DO: Login as Admin
DO: Use Big Picture Snippet 
DO: add full hd image as picture 
DO: save and test it with chrome --> WORKS fullscreen, mobile less 800px aso... android, mac, works ...
DO: Iexplore smaller than 800 px till it switches to mobile menü .... page scales immediately to 100% 
DO: Windows mobile phone --> same problem mobile version does not show correctly

**Comment by michaelkarrer81** [comment]
Geschlossen solange sich nicht ein Kunde beschwert
