### ISSUE TITLE
Check / Change php5-fpm from ip to socket

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/odoo_v8.0#9]
Make sure PHP-FPM is listening on unix socket and not on IP!

/etc/php5/fpm/pool.d/www.conf

...
; The address on which to accept FastCGI requests.
; Valid syntaxes are:
;   'ip.add.re.ss:port'    - to listen on a TCP socket to a specific address on
;                            a specific port;
;   'port'                 - to listen on a TCP socket to all addresses on a
;                            specific port;
;   '/path/to/unix/socket' - to listen on a unix socket.
; Note: This value is mandatory.
;listen = 127.0.0.1:9000
listen = /var/run/php5-fpm.sock
...

**Comment by michaelkarrer81** [comment]
Check was betroffen ist

**Comment by michaelkarrer81** [comment]
das ist sonst ein problem für owncloud welches über nginx und php-fpm geserved wird

**Comment by winston6071** [comment]
write the fpm.sock stuff into the config file after fpm installation of fpm modules is done
